name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake -DHULA_BUILD_DEMOS=ON ..
        make
    - name: test
      run: |
        cd build
        ctest
