name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: fetch dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y catch2
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake -DHULA_BUILD_DEMOS=ON ..
        make
    - name: test
      run: |
        cd build
        ctest --output-on-failure

  build_coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: fetch dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y catch2 gcov
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake -DHULA_BUILD_DEMOS=ON -DHULA_COVERAGE=ON ..
        make
    - name: test
      run: |
        cd build
        ctest -T coverage --output-on-failure

